import assert from 'node:assert/strict';
import test from 'node:test';
import { classifyFile } from '../analyzers/fileClassifier';
import { scoreChanges } from '../analyzers/importanceAnalyzer';
import { detectRisks } from '../analyzers/riskAnalyzer';
import { generateStories } from '../analyzers/storyGenerator';
import { FileChange } from '../models/change';
test('classifies security and UI files', () => { assert.equal(classifyFile('src/auth/auth.service.ts'), 'Authentication'); assert.equal(classifyFile('src/components/Button.tsx'), 'UI'); });
test('security changes outrank large UI churn', () => { const security: FileChange = { path: 'auth.ts', status: 'M', additions: 20, deletions: 4, category: 'Authentication', symbols: [], flags: [], imports: [], importance: 'HIGH', score: 0, diff: '' }; const ui: FileChange = { path: 'styles.css', status: 'M', additions: 500, deletions: 200, category: 'UI', symbols: [], flags: [], imports: [], importance: 'LOW', score: 0, diff: '' }; assert.ok(scoreChanges([security]).score > scoreChanges([ui]).score); });
test('large fixture is scored without quadratic work', () => { const files = Array.from({ length: 2000 }, (_, index) => ({ path: `src/file${index}.ts`, status: 'M', additions: 5, deletions: 2, category: 'Backend' as const, symbols: [] as string[], flags: [] as string[], imports: [] as string[], importance: 'LOW' as const, score: 0, diff: '' })); assert.ok(scoreChanges(files).score <= 100); });
test('risk findings include actionable inspection guidance', () => { const file: FileChange = { path: 'src/auth/middleware.ts', status: 'M', additions: 20, deletions: 4, category: 'Authentication', symbols: ['verifyToken'], flags: [], imports: [], importance: 'CRITICAL', score: 90, diff: '' }; const risk = detectRisks([file])[0]; assert.equal(risk.level, 'CRITICAL'); assert.match(risk.recommendation, /token validation/i); });
test('related files become one story', () => { const files: FileChange[] = ['auth.ts', 'middleware.ts'].map(path => ({ path, status: 'M', additions: 10, deletions: 2, category: 'Authentication', symbols: [], flags: [], imports: [], importance: 'HIGH', score: 60, diff: '' })); const stories = generateStories(files, []); assert.equal(stories.length, 1); assert.equal(stories[0].files.length, 2); });
